message:
  signInMessage: "[>>] Инфо: "
  notAPlayer: "Вы не являетесь игроком!"
  SetWarp:
    setWarpHelp: "Использование: /setwarp <name>"
    setWarpContains: "Варп с таким названием уже существует!"
    setWarpPut: "Вы успешно создали варп с названием {name}"
  DelWarp:
    delWarpHelp: "Использование: /delwarp <name>"
    delWarpNull: "Варп не найден {name}"
    delWarpNoOwner: "Вы не являетесь владельцем варпа!"
  Warp:
    WarpHelp: "Использование: /warp <name>"
    WarpNull: "Варп не найден {name}"
    WarpPut: "Вы успешно телепортировались на варп {name}"



