message:
  prefix: "&c&l&oPERDO: "
  checking: "&cВы не являетесь игроком"
  permission: "&cУ вас нет прав"

  command:
    workbench:
      open: "&aВы успешно открыли виртуальный верстак"
    enderchest:
      open: "&aВы успешно открыли виртуальный сундук"
    ext:
      noSuccesful: "&7Вы не горите"
      succesful: "&7Вы были потушены"
    fly:
      disable: "&7Вы выключили режим полета"
      enable: "&7Вы включили режим полета"
    god:
      disable: "&7Вы выключили режим бессмертия"
      enable: "&7Вы включили режим бессмертия"
    hat:
      item: "&cУ вас нет предмета в руке"
      succesful: "&aВы успешно одели предмет на голову"
    invsee:
      usage: "&7/invsee &c<name>"
      player: "&cИгрок не найден"
      open: "&aВы успешно открыли инвентарь игрока &c{player}"
    milk:
      noSuccesful: "&7У вас нет негативных эффектов"
      succesful: "&aВы успешно очистили с себя негативные эффекты"
    near:
      find: "&cРядом с вами нет игроков"
    teleport:
      tpUsage: "&7/tp &c<name>"
      tpaUsage: "&7/tpa &c<name>"
      tpaRequestPlayer: "&7Вы отправили запрос на телепортацию &c{player}"
      tpaRequestTargetPlayer: "&c{player} &7отправил вам запрос на телепортацию. Введите &c/tpaccept &fчтобы принять, &c/tpdeny чтобы отклонить"
      succesful: "&7Вы телепортировались к &c{player}"
      player: "&cИгрок не найден"
      acceptTargetPlayer: "&aВы приняли запрос на телепортацию"
      acceptPlayer: "&aЗапрос на телепортацию был принят"
      denyTargetPlayer: "&cВы отклонили запрос на телепортацию"
      denyPlayer: "&cЗапрос на телепортацию был отклонен"
      request: "&cВам никто не отправлял запрос на телепортацию"
      noTp: "&cВы не можете телепортироваться к себе!"
    warp:
      warpUsage: "&7/warp &c<name>"
      setWarpUsage: "&7/setwarp &c<name>"
      delWarpUsage: "&7/delwarp &c<name>"
      tp: "&7Вы телепортировались на варп &c{name}"
      find: "&7Варп &c{name} &7не найден"
      create: "&7Вы создали варп &c{name}"
      exists: "&7Варп &c{name} &7уже существует"
      delete: "&7Вы удалили варп &c{name}"
      creator: "&cВы не владелец варпа"
    feed:
      succesful: "&aВы успешно восстановили голод"
    repair:
      succesful: "&aВы успешно починили предмет в вашей руке"
      item: "&cУ вас нет предмета в руке"
    home:
      homeUsage: "&7/home &c<name>"
      setHomeUsage: "&7/sethome &c<name>"
      delHomeUsage: "&7/delhome &c<name>"
      tp: "&7Вы телепортировались на точку дома &c{name}"
      find: "&7Точка дома &c{name} &7не найдена"
      create: "&7Вы создали точку дома &c{name}"
      delete: "&7Вы удалили точку дома &c{name}"
    endersee:
      enderSeeUsage: "&7Использование: &c/endersee <name>"
      open: "&7Вы открыли эндер-сундук {name}"
    reload:
      succesful: "&aВы успешно перезагрузили плагин!"
