message:
  prefix: "&c&l&oPERDO: "
  checking: "&7&oВы не являетесь игроком!"
  permission: "&7&oУ вас нет прав!"

  command:
    workbench:
      open: "&7&oВы успешно открыли виртуальный верстак!"
    enderchest:
      open: "&7&oВы успешно открыли виртуальный сундук!"
    ext:
      noSuccesful: "&7&oВы не горите!"
      succesful: "&7&oВы были потушены!"
    fly:
      disable: "&7&oВы выключили режим полета!"
      enable: "&7&oВы включили режим полета!"
    god:
      disable: "&7&oВы выключили режим бессмертия!"
      enable: "&7&oВы включили режим бессмертия!"
    hat:
      item: "&7&oУ вас нет предмета в руке!"
      succesful: "&7&oВы успешно одели предмет на голову!"
    invsee:
      usage: "&7&o/invsee <name>"
      player: "&7&oИгрок не найден!"
      open: "&7&oВы успешно открыли инвентарь игрока {player}"
    milk:
      noSuccesful: "&7&oУ вас нет негативных эффектов!"
      succesful: "&7&oВы успешно очистили с себя негативные эффекты!"
    near:
      find: "&7&oРядом с вами нет игроков!"
    teleport:
      tpUsage: "&7&o/tp <name>"
      tpaUsage: "&7&o/tpa <name>"
      tpaRequestPlayer: "&7&oВы отправили запрос на телепортацию {player}"
      tpaRequestTargetPlayer: "&6&o{player} &7&oотправил вам запрос на телепортацию. Введите /tpaccept чтобы принять, /tpdeny чтобы отклонить."
      succesful: "&7&oВы телепортировались к &6&o{player}"
      player: "&7&oИгрок не найден!"
      acceptTargetPlayer: "&7&oВы приняли запрос запрос на телепортацию!"
      acceptPlayer: "&7&oЗапрос на телепортацию был принят!"
      denyTargetPlayer: "&7&oВы отклонили запрос на телепортацию!"
      denyPlayer: "&7&oЗапрос на телепортацию был отклонен!"
      request: "&7&oВам никто не отправлял запрос на телепортацию!"
    warp:
      warpUsage: "&7&o/warp <name>"
      setWarpUsage: "&7&o/setwarp <name>"
      delWarpUsage: "&7&o/delwarp <name>"
      tp: "&7&oВы успешно телепортировались на варп &6&o{name}"
      find: "&7&oВарп &6&o{name} &7&oне найден!"
      create: "&7&oВы успешно создали варп &6&o{name}"
      exists: "&7&oВарп &6&o{name} &7&oуже существует!"
      delete: "&7&oВы успешно удалили варп &6&o{name}"
      creator: "&7&oВы не владелец варпа!"
    food:
      succesful: "&7&oВы успешно восстановили голод!"
    repair:
      succesful: "&7&oВы успешно починили предмет в вашей руке!"
      item: "&7&oУ вас нет предмета в руке!"
    home:
      homeUsage: "&7&o/home <name>"
      setHomeUsage: "&7&o/sethome <name>"
      delHomeUsage: "&7&o/delhome <name>"
      tp: "&7&oВы успешно телепортировались на точку дома &6&o{name}"
      find: "&7&oТочка дома &6&o{name} &7&oне найдена!"
      create: "&7&oВы успешно создали точку дома &6&o{name}"
      delete: "&7&oВы успешно удалили точку дома &6&o{name}"
    reload:
      succesful: "&7&oВы успешно перезагрузили плагин!"
