
hexColor: "#00ff00"
bold: true

message:
  prefix: "[>>] "
  checking: "&fВы не являетесь игроком"
  permission: "&fУ вас нет прав"

  command:
    workbench:
      open: "&fВы открыли виртуальный верстак"
    enderchest:
      open: "&fВы открыли виртуальный сундук"
    ext:
      noSuccesful: "&fВы не горите"
      succesful: "&fВы были потушены"
    fly:
      disable: "&fВы выключили режим полета"
      enable: "&fВы включили режим полета"
    god:
      disable: "&fВы выключили режим бессмертия"
      enable: "&fВы включили режим бессмертия"
    hat:
      item: "&fУ вас нет предмета в руке"
      succesful: "&fВы одели предмет на голову"
    invsee:
      usage: "&f/invsee &6<игрок>"
      player: "&fИгрок не найден"
      open: "&fВы открыли инвентарь игрока &6{player}"
    milk:
      noSuccesful: "&fУ вас нет негативных эффектов"
      succesful: "&fВы очистили с себя негативные эффекты"
    near:
      find: "&fРядом с вами нет игроков"
    teleport:
      tpUsage: "&f/tp &6<игрок>"
      tpaUsage: "&f/tpa &6<игрок>"
      tpaRequestPlayer: "&fВы отправили запрос на телепортацию &6{player}"
      tpaRequestTargetPlayer: "&6{player} &fотправил вам запрос на телепортацию. Введите &6/tpaccept &fчтобы принять, &6/tpdeny чтобы отклонить"
      succesful: "&fВы телепортировались к &6{player}"
      player: "&fИгрок не найден"
      acceptTargetPlayer: "&fВы приняли запрос на телепортацию"
      acceptPlayer: "&fЗапрос на телепортацию был принят"
      denyTargetPlayer: "&fВы отклонили запрос на телепортацию"
      denyPlayer: "&fЗапрос на телепортацию был отклонен"
      request: "&fВам никто не отправлял запрос на телепортацию"
      noTp: "&fВы не можете телепортироваться к себе!"
    warp:
      warpUsage: "&f/warp &6<название>"
      setWarpUsage: "&f/setwarp &6<название>"
      delWarpUsage: "&f/delwarp &6<название>"
      tp: "&fВы телепортировались на варп &6{name}"
      find: "&fВарп &6{name} &fне найден"
      create: "&fВы создали варп &6{name}"
      exists: "&fВарп &6{name} &fуже существует"
      delete: "&fВы удалили варп &6{name}"
      creator: "&fВы не владелец варпа"
    feed:
      succesful: "&fВы восстановили голод"
    repair:
      succesful: "&fВы успешно починили предмет в вашей руке"
      item: "&fУ вас нет предмета в руке"
    home:
      homeUsage: "&f/home &6<название>"
      setHomeUsage: "&f/sethome &6<название>"
      delHomeUsage: "&f/delhome &6<название>"
      tp: "&fВы телепортировались на точку дома &6{name}"
      find: "&fТочка дома &6{name} &fне найдена"
      create: "&fВы создали точку дома &6{name}"
      delete: "&fВы удалили точку дома &6{name}"
    endersee:
      enderSeeUsage: "&f/endersee &6<игрок>"
      open: "&fВы открыли эндер-сундук &6{name}"
    reload:
      succesful: "&fВы перезагрузили плагин"

database:
  url: ""
  username: ""
  password: ""