name: Addons
version: '1.0-SNAPSHOT'
main: phrase.addons.Addons
api-version: '1.18'
commands:
  workbench: {}
  ec: {}
  hat: {}
  invsee: {}
  setwarp: {}
  warp: {}
  delwarp: {}
  ext: {}
  tp: {}
  tpa: {}
  tpaccept: {}
  tpdeny: {}
  fly: {}
  milk: {}
  near: {}
  endersee: {}
  feed: {}
  home: {}
  sethome: {}
  delhome: {}
  repair: {}
  addons: {}



